### ISSUE TITLE
provide german verbose date for tei:title

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/schnitzler-tagebuch#12]
currently `<title type="main">Eintrag vom: 1879-12-01</title>`
though allegedly some 20th century users prefer something like `Montag, 1. Dezember 1879`

**Comment by martinantonmueller** [comment]
Some 20th century users might even be so picky to have no leading zeros and a small non-breaking-space after the dot, i.e.: 1.¦Mai␣2006 (Legende: Das übliche Leerzeichen ist hier durch „␣“, das schmale Leerzeichen durch „¦“ dargestellt.) HexCode: `&#x2009;`
