### ISSUE TITLE
don't process tei:fw

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/schnitzler-tagebuch#13]
I guess we don't want to see things like in the html output as in e.g. [entry__1879-12-01.xml](/pages/show.html?document=entry__1879-12-01.xml&directory=editions)
```xml
<tei:fw type="header">
  <fw place="top_left" type="pageNum">14</fw>
  <fw place="top_center">
    <date type="range">1879: XII 1 - XII 15</date>
  </fw>
</tei:fw>
````

**Comment by martinantonmueller** [comment]
Yes, I would not want to see that. The information can be accessed by clicking on the PDF of the printed version
