### ISSUE TITLE
provide images and texts for grid on startpage

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/schnitzler-tagebuch#14]

**Comment by martinantonmueller** [comment]
Image for Personenindex:
[https://wellcomecollection.org/works/xhnevz32](https://wellcomecollection.org/works/xhnevz32
)showing the girls in a row and the guy measuring them

City map for the Ortsindex:
[https://upload.wikimedia.org/wikipedia/commons/1/1e/Umgebung_von_Wien_%28Einseitige_Farbkarte%29.jpg](https://upload.wikimedia.org/wikipedia/commons/1/1e/Umgebung_von_Wien_%28Einseitige_Farbkarte%29.jpg)

**Comment by martinantonmueller** [comment]
Explanatory text to the main header:

> 16.412 Einträge notierte der Schriftsteller Arthur Schnitzler in sein Tagebuch. Sie geben Auskunft über das Leben des Wiener Schriftstellers, die Begegnungen, die er machte und die Gespräche die er führte.

Text for Personen:

Shorten title to: **Personenverzeichnis**

> Einstieg über das Personenregister mit über 8500 nachgewiesenen Personen und ihrem Vorkommen im Tagebuch.

===

Text for places:

Shorten title to **Ortsverzeichnis**

> Zugang zum Tagebuch mittels 2200 Orten, die auch über ihre Koordinaten erschlossen sind. 

===
Text for calendar:

> Fünfzig Jahre lang legte Schnitzler nahezu täglich Einträge an. Über den Kalender können bestimmte Tage direkt aufgefunden werden.
