### ISSUE TITLE
bibl

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-tagebuch#22]
There are 9 instances were "bibl" is tagged. Currently the ouptut is bold-font, i.e.
https://schnitzler-tagebuch.acdh.oeaw.ac.at/pages/show.html?document=entry__1887-10-19.xml&directory=editions
Output should be just regular font

**Comment by csae8092** [comment]
added
```xsl
<xsl:template match="tei:bibl">
    <xsl:apply-templates/>
</xsl:template>
```
to resources/xsl/editions.xsl
