### ISSUE TITLE
geodata in search results

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-tagebuch#30]
When search results contain places sometimes their geodata is shown, i.e.:

![SchnitzlerGeodatenSemmering](https://user-images.githubusercontent.com/11441262/76937046-48264d00-68f4-11ea-9e66-e8dde7d577da.JPG)

**Comment by csae8092** [comment]
the KWIC result is produced by a function provided by eXist-db (`kwic:summarize`); so I'd prefere not to hack much araound there; one could of course make the kwic-window smaller, but by doing so, one would use maybe useful context information. So I close this issue now.
