### ISSUE TITLE
duplication issue in search results

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-tagebuch#31]
when there are more than one results in the same entry the search result contains the snippet twice:
![SchnitzlerGrazVerdoppelung](https://user-images.githubusercontent.com/11441262/76937125-7c017280-68f4-11ea-93e5-6d861e15edc9.JPG)
![SchnitzlerSalzburgdoppelt](https://user-images.githubusercontent.com/11441262/76937142-8459ad80-68f4-11ea-888f-5a14606978ca.JPG)

**Comment by csae8092** [comment]
this is actually the intended behavior: showing the context of each hit; so I'd prefer to keep this
