### ISSUE TITLE
show entities in detail view

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/schnitzler-tagebuch#36]
find a nice looking way to show entities in detail view of diary entry

e.g. entry__1922-09-16.xml

**Comment by martinantonmueller** [comment]
I've just implemented something similar to the schnitzler-briefe-app, but I don't believe it can just be copied for your task
https://schnitzler-briefe.acdh.oeaw.ac.at/pages/show.html?document=L00919.xml&stylesheet=links
