### ISSUE TITLE
Seitenwechsel der Buchausgabe im Text verbergen

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/schnitzler-tagebuch#8]
Z.B. hier:  http://localhost:8080/exist/apps/schnitzler-tagebuch/pages/show.html?document=entry__1916-06-27.xml&directory=editions

Das ist durch den Link auf das Buch-PDF sowieso obsolet. Und wirklich relevant wären eher die Seitenwechsel der Faksimiles

**Comment by csae8092** [comment]
fixed with commit https://github.com/acdh-oeaw/schnitzler-tagebuch/commit/1c6185eb3d050dab99556e91b9407b7d36366d1e
